### ISSUE TITLE
When I turn wi-fi on. It crashes. 

### ISSUE THREAD

**Issue by Comodore125** [HashEngineering/dash-wallet#16]
And It displays info about previous crash. I want to send it, but wi-fi crashes it. 

The same for testnet version. 

My phone is stable, only this is doing these things.

**Comment by HashEngineering** [comment]
Thanks for reporting this.

We haven't seen this error before and would really like to get a crash
report.

If you could could use wifi so the app crashes, then turn off wifi before
starting the app again to send the report that would be great.  Of course
in some cases the app starts itself again quickly and sending out the
report without wifi may be impossible.

Of you can't send the report, then tell us what Android version you are
using and the model of your device.  Thanks.

**Comment by Comodore125** [comment]
hashengineeringsolutions@gmail.com I sent it there fortunately

**Comment by HashEngineering** [comment]
Thanks, the crash report was relieved.  Looks like we might have two users
with this issue.

**Comment by Comodore125** [comment]
I am looking for a fix :)

**Comment by HashEngineering** [comment]
Does this happen after sending a transaction?  Meaning the app worked, until a transaction was sent.  Then it started crashing all the time?  That is what the error message is suggesting in the logs.

**Comment by Comodore125** [comment]
yes. I already deleted blockchain in offline mode and then I was able to continue without further crashing.

**Comment by HashEngineering** [comment]
When you were able to continue, was WIFI ON or OFF?

**Comment by joshafest** [comment]
It may be "Network on main thread issue" or maybe network..

@Comodore125 would you please check it by disconnecting data (mobile data) with wi fi off
and run apk?

**Comment by HashEngineering** [comment]
This issue was caused by a missing line of code when the transaction was created.  The missing line would set the status of the tx to PENDING, then the app would send out the transaction.  In some cases with no network connectivity, no response from the network was received (which would also set the tx status to PENDING.  Later the app would connect and it would have a transaction stayed with an UNKNOWN status to be sent out (because the app didn't know if it was sent out yet).  There was a check the tx status to make sure all the transactions that the app thought should be sent out were PENDING.  If a tx wasn't pending, then the app would throw an exception that wasn't caught, then crash.

The next update 4.65.12A resolved part of this issue because it wasn't missing that line of code, but it didn't have a fix for apps that were already in this crash cycle.  4.65.12D addressed this issue.  Though the app may require a block chain reset in some cases.
