### ISSUE TITLE
Damn these fees

### ISSUE THREAD

**Issue by Comodore125** [HashEngineering/dash-wallet#17]
Fees are too damn high. 
No way to set them. 

Please change this. I want to have a choice. 

I have just noticed that normal/economic/priority - is the same. And this setting is actualy hard to find.

**Comment by HashEngineering** [comment]
In the source code, the fee for economic is 1000 Satoshi, 5000 Satoshi for Normal and 10000 Satoshi for Priority.

Dash requires 1000 Satoshi.  We can change the levels, but it will be a lot of work to add a feature to have the user type in the fee they want to pay.  In the past the Bitcoin Wallet had this feature and this resulted in many stuck transactions because they didn't have enough of a fee.  Therefore, the Bitcoin Wallet developers made fees mandatory (which is also because the app is an SPV client and cannot determine if the transaction can be free).  Later they added in three levels of fees to help transactions get confirmed in the very busy bitcoin network.
