### ISSUE TITLE
BUG: dash-wallet barcode reader flip-flops image on Android Nexus 5x

### ISSUE THREAD

**Issue by taw00** [HashEngineering/dash-wallet#5]
_Sorry for the cross-posting. I sent this as an email as well._

Please read this. You are doing it wrong. :)
http://www.androidcentral.com/google-reveals-why-some-photos-taken-nexus-5x-are-upside-down

Summary: The spec says that the image chip can be in one of two ways. But almost all phones engineer it one particular way. App writers (such as you guys) assume that is The Way it is supposed to work. Alas, Nexus 5x -- a very popular smartphone -- has nicely uncovered all the apps that made this assumption and flip-flop the image.

It makes scanning QR codes challenging. Don't feel terrible. You are not the only app for which I am filing a very similar bug.

**Comment by HashEngineering** [comment]
This issue may be fixed in the beta test version of the Dash Wallet.  We are working on some other fixes and will be ready to roll out another test version soon.  Unfortunately the current beta version has some other bugs with scanning QR codes, so I don't recommend trying it to see if we fixed the problem. 

The above linked article says we need to update to use the most recent Google Libraries, which we are doing in the beta (which also does more instantx processing).

**Comment by HashEngineering** [comment]
This is still not fixed.

**Comment by HashEngineering** [comment]
We have pulled updates from Bitcoin wallet and will have a test version in one week to see if it resolves the issue.

**Comment by HashEngineering** [comment]
We haven't received any reports that this is still an issue.

**Comment by taw00** [comment]
I filed it. It's resolved. Closing.
