### ISSUE TITLE
Not able to create build variant in _testNet3Release and prodRelease

### ISSUE THREAD

**Issue by jaydeep82** [HashEngineering/dash-wallet#79]
I'm getting following errors when trying to create build using Gradle build tool 2.10

> 
> Error:Failed to complete Gradle execution.
> 
> Cause:
> The version of Gradle you are using (2.10) does not support the forTasks() method on BuildActionExecuter. Support for this is available in Gradle 3.5 and all later versions.

Can we upgrade it to Gradle build version 3.5 and above? So we can create build in release mode.

Android Studio 3.0.1
Branch : wallofcoins

**Comment by HashEngineering** [comment]
We currently use 2.10 because that is what Bitcoin Wallet currently uses and we don't have any issues compiling and building release versions.  Bitcoin Wallet was using 2.10 because at the time, 2.10 was the version that came with Ubuntu by default with `apt-get`.  We do want to consider that others will be building this project from source on various systems.

What changes did you make that require using a higher Gradle build version?
